from entities import Level


LEVELS = [Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                       B',
	'B                       B',
	'B                       B',
	'B   BBBBB BB BB BBBB    B',
	'B               BBBB    B',
	'B B    BBBBBBBBBBBBB    B',
	'B BB   B          BBBBB B',
	'B BBB  B          B     B',
	'B      B          B BBBBB',
	'B   BBBB   B      B     B',
	'B      B   B B    BBBBB B',
	'B B    B   B      B     B',
	'B BB   B   BB     B BBBBB',
	'B BBB  B   BBB          B',
	'B BBBB B   BBBBBBBBBBBBBB',
	'B      B                B',
	'B BBBBBBBBBBBBBBBBBBBBB B',
	'B BBBBBBE               B',
	'BBBBBBBBBBBBBBBBBBBBBBBBB'], [["I wanted to make you a gift which would mean something to you, but I wasn't sure what.", [64, 32]]], [32, 32]),
	Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                       B',
	'B                       B',
	'B                       B',
	'B   BBB   BB    BBBBBBBBB',
	'B               CCCC    B',
	'B B    BCCCCCCCCCCCC    B',
	'B BB   B          CCCBB B',
	'B BBB  B          B     B',
	'B      B          B BBBBB',
	'B   BBBB   B      B     B',
	'B      B   B B    BBBBB B',
	'B B    B   B      B     B',
	'B BB   B   BB     B BBBBB',
	'B BBB  B   BBB          B',
	'B BBBB B   BBBBBBBBBBBBBB',
	'B      B                B',
	'B BBBBBBBBBBBBBBBBBBBBB B',
	'B BBBBBBE               B',
	'BBBBBBBBBBBBBBBBBBBBBBBBB'], [["If I could write music, or poetry, or draw a beautiful portrait, I would, but code is my creativity.", [64, 32]]], [32, 32]),
	Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                    BBBB',
	'B                    BBBB',
	'B                   EBBBB',
	'B                BBBBBBBB',
	'B               BBBBBBBBB',
	'B              BBBBBBBBBB',
	'B             BBBBBBBBBBB',
	'B            BBBBBBBBBBBB',
	'B           BBBBBBBBBBBBB',
	'B          BBBBBBBBBBBBBB',
	'B         BBBBBBBBBBBBBBB',
	'B        BBBBBBBBBBBBBBBB',
	'B       BBBBBBBBBBBBBBBBB',
	'B      BBBBBBBBBBBBBBBBBB',
	'B     BBBBBBBBBBBBBBBBBBB',
	'B    BBBBBBBBBBBBBBBBBBBB',
	'B   BBBBBBBBBBBBBBBBBBBBB',
	'B BBBBBBBBBBBBBBBBBBBBBBB',
	'BBBBBBBBBBBBBBBBBBBBBBBBB'], [["Things haven't ever felt like an upward struggle.", [64, 32]]], [32, 32]),
    Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                   IIIIB',
	'B                   IIIIB',
	'B                   IIIIB',
	'B                IIIIIIIB',
	'B               IIIIIIIIB',
	'B              IIIIIIIIIB',
	'B             IIIIIIIIIIB',
	'B            IIIIIIIIIIIB',
	'B           IIIIIIIIIIIIB',
	'B          IIIIIIIIIIIIIB',
	'B         IIIIIIIIIIIIIIB',
	'B        IIIIIIIIIIIIIIIB',
	'B       IIIIIIIIIIIIIIIIB',
	'BCC    IIIIIIIIIIIIIIIIIB',
	'BEC   IIIIIIIIIIIIIIIIIIB',
	'BBBIIIIIIIIIIIIIIIIIIIIIB',
	'BIIIIIIIIIIIIIIIIIIIIIIIB',
	'BIIIIIIIIIIIIIIIIIIIIIIIB',
	'BBBBBBBBBBBBBBBBBBBBBBBBB'], [["We always seem to work past things others would think were obstacles.", [64, 32]]], [19*32, 3*32]),
	Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'BIIIIIIIIIIIIIIIIIIII   B',
	'BIIIIIIIIIIEIIIIIIIII   B',
	'B                       B',
	'BBBBBBBBBBBBBBBBBBBBBBBBB',], [["The way we seem always to stay afloat is magical.", [64, 32]]], [32, 15*32]),
	Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'BCBBBBBBBBBBBBBBBBBBBBCCB',
	'BEI                     B',
	'BBBBBBBBBBBBBBBBBBBBBBBBB',], [["After all all, things often seem too good to be true.", [64, 32]]], [32*10, 32*17]),
	Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                      EB',
	'B                   BBBBB',
	'BBBBB               BBBBB',
	'BBBBB                   B',
	'B                BBB    B',
	'B              BB       B',
	'B                       B',
	'B                       B',
	'B            BBB        B',
	'B                   BBBBB',
	'B       CCCC        BBBBB',
	'B       CCCC      BB    B',
	'B                       B',
	'B   BBBBBBB     BBBB    B',
	'B                       B',
	'B           BBBB        B',
	'B       BBB             B',
	'B  BBBBBBBB             B',
	'BBBBBBBBBBBBBBBBBBBBBBBBB'], [["So, I can't write you a poem. But If I could, it would say...", [64, 32]]], [32, 32]),
	Level([
	'BBBBBBBBBBBBBBBBBBBBBBBBB',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                       B',
	'B                      EB',
	'BBBBBBBBBBBBBBBBBBBBBBBBB'
	], [["...\"I love you.\".", [64, 32]]], [32, 18*32])]
